### ISSUE TITLE
Thumbnails are not generated.

### ISSUE THREAD

**Issue by danslo** [danslo/hhvm#18]
HHVM throws a "Destructor raised a fatal error: Unexpected object type Unknown.".

**Comment by danslo** [comment]
Seems to work for me. Other people reporting this as an issue. Input is welcome.

**Comment by swieczorek** [comment]
i have recompiled hhvm and i have still the issue.
After clearing the thumbnail cache media/catalog/product/cache/\* , hhvm does not generate thumbnails and generates your mentioned error message.

**Comment by swieczorek** [comment]
I found the problem. The problem occured because of a memory limit in Varien_Image_Adapter_Gd2 Line 58

https://gist.github.com/swieczorek/7840516

ini_set('memory_limit', '512M'); in index.php solves the issue.
The better solution is probably to use the php.ini

**Comment by danslo** [comment]
@swieczorek Ok so it's the same problem I solved before:
https://github.com/danslo/hhvm/issues/16

See my wiki as proper solution to this :)
