### ISSUE TITLE
MySQL connections not properly closed.

### ISSUE THREAD

**Issue by danslo** [danslo/hhvm#21]
This seems to cause "too many connection" errors with the mysql service.

**Comment by kandy** [comment]
As workaround I use

```
register_shutdown_function(function($con) {   if ($con) { $con->closeConnection(); }  }, $this);
```

in Mysql Adapter

**Comment by danslo** [comment]
@kandy: Thanks. Do you have any clue what's happening in the code? Something not being called at end of request? Magento just not properly closing it?

**Comment by kandy** [comment]
Looks like problem in HipHop PDO implementation.
php version is auto close connection in destructor, but in hiphop doesn't do

**Comment by danslo** [comment]
It's probably a refcount issue. Varien_Db_Adapter_Pdo_Mysql::__destruct is never called.

**Comment by danslo** [comment]
Follow the following PR for a possible fix: 
https://github.com/facebook/hhvm/pull/1345

**Comment by danslo** [comment]
Fixed in https://github.com/danslo/hhvm/tree/pdo-connection-closer - Just need to wait for it to be merged.
