### ISSUE TITLE
fastcgi_pass not working from nginx => hhvm

### ISSUE THREAD

**Issue by cscd98** [danslo/hhvm#27]
I am using fastcgi_param in nginx location block to set the MAGE_RUN_CODE but the value is not set in php. I can verify this by echoing $mageRunCode from index.php from Magento.

vhost snippet from nginx:

```
location ~ \.php$ {
        # Catch 404s
        if (!-e $request_filename) {
            rewrite / /index.php last;
        }

        # Do not cache dynamic content
        expires        off;

        fastcgi_pass   127.0.0.1:9000; 

        fastcgi_param  SCRIPT_FILENAME           $document_root$fastcgi_script_name;
        fastcgi_param  MAGE_RUN_CODE             store_code;
        fastcgi_param  MAGE_RUN_TYPE             website;

        include        fastcgi_params;

    }
```

**Comment by danslo** [comment]
I appreciate the report, but I'm going to close this in favor of keeping track of this in https://github.com/facebook/hhvm/issues/1232 since it affects (a lot) more than Magento.

**Comment by cscd98** [comment]
The fix for fastcgi params has been merged now - any chance you could pull down the changes to yours? Thanks.  Not sure if the SERVER vars fix is included.

**Comment by danslo** [comment]
@craigcarnell Done!

**Comment by cscd98** [comment]
I've just got to say fantastic support :+1: 

Any chance of you merging master again, this time hopefully HTTPS will be set properly in $_SERVER array

https://github.com/facebook/hhvm/commit/f1fdcdd8abc95f299a048f5eac7cebc2801056c2

**Comment by danslo** [comment]
@craigcarnell I've rebased once more :-) Should be ok now.
