### ISSUE TITLE
checkout button failing.

### ISSUE THREAD

**Issue by ajbird2** [danslo/hhvm#28]
I am seeing this on two sites.. 1 being a default demo store install.  In the case of the demo store clicking 'place order' with check / money order results in submitting order information icon spinning till it times out and the user bounces back to cart.. 

In the other (non-demo store) site the 'Place order' button simply does nothing.. 

though all test orders show as pending in Sales list... any ideas?

It seems such a strange issue considering everything else seems to work perfectly.

using hhvm + fastcgi via nginx

**Comment by ajbird2** [comment]
[error] 476#0: *501 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 82.7.137.2, server: hiphop.testing123.com, request: "POST /checkout/onepage/saveOrder/form_key/gmJYYdq1mN54gZ5Y/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "hiphop.testing123.com", referrer: "http://hiphop.testing123.com/checkout/onepage/"

**Comment by mklooss** [comment]
did u checked if hhvm is running after this error?
may u have to change the value of "fastcgi_read_timeout" in nginx

**Comment by ajbird2** [comment]
OK you can close this.. the problem was magento was trying to send an email.. failed and the whole thing stopped.. Once I routed email through mandrilapp all is again well.

**Comment by mklooss** [comment]
may u did not configured sendmail?
https://github.com/facebook/hhvm/wiki/runtime-options#mail

**Comment by danslo** [comment]
Closing this re @ajbird2's comment. Stefan found an issue that may be related (or the same), let's focus the attention on that ticket.
https://github.com/danslo/hhvm/issues/30
