### ISSUE TITLE
Admin session serialization incompatibility between hhvm and php-fpm

### ISSUE THREAD

**Issue by jaredkipe** [danslo/hhvm#29]
Lets say that you have fastcgi pass between nginx and hhvm.  You go into admin interface, and log in.  (database storage of sessions)

Now you stop hhvm, and start php-fpm (listening on the same TCP port).
Refresh the page, and you will get a white screen of death in Magento.

Error will be backtrace in ACL, and it appears that this is because Magento serializes ACL related objects into the session, and while both HHVM and PHP-FPM are fine using the unserialized versions of their own sessions, they cannot share between the two.

If you clean up sessions/cookies and repeat the process from PHP-FPM to HHVM, hhvm will display login page and generate a new session.

**Comment by jaredkipe** [comment]
https://gist.github.com/jaredkipe/822cd5f73f7230053c89
Run that file through hhvm and the rest of magento through php-fpm (or other way around)

**Comment by danslo** [comment]
Do you have any chance to trace this down to a pure PHP (without Magento) repro? I probably won't have time to look at this for the next couple of weeks.

**Comment by jaredkipe** [comment]
It appears to have to do with serializing the permissions objects related to adminhtml.  The front end cookie appears to transfer just fine between the two.

**Comment by danslo** [comment]
Fixed by
https://github.com/facebook/hhvm/pull/2092
and
https://github.com/facebook/hhvm/pull/2075
