### ISSUE TITLE
HipHop Fatal error: f_stream_socket_enable_crypto is not going to be supported: no crypto support on sockets in lib/Zend/Mail/Protocol/Smtp.php on line 206

### ISSUE THREAD

**Issue by swieczorek** [danslo/hhvm#30]
I get this error in the checkout when i push the button "submit Order".

Magento Version: 1.5.1.0
HipHop VM v2.4.0-dev (rel)
Compiler: heads/master-0-g7efde93c5912243e8a7c7365d1cb601410b56871
Repo schema: 1598bc495c7b630e701bcc45135011031fee1ff6
FastCGI: no

**Comment by jaredkipe** [comment]
This is a core HHVM issue, namely that you are using an SMTP server /port that requires encryption.  HHVM does not support that, as of yet.
https://github.com/facebook/hhvm/issues/1647

**Comment by danslo** [comment]
Going to close this in favor of tracking it in the main repository.
