### ISSUE TITLE
SoapClient doesn't follow 302 redirect

### ISSUE THREAD

**Issue by rbrown** [danslo/hhvm#37]
Hi, this is either a bug, or just a misconfiguration on my part. I noticed that VAT validation was failing on my store after switching to hhvm, tested it, and the problem is that hhvm is not following a 302 redirect from vies.

``` php
<?php
new SoapClient('http://ec.europa.eu/taxation_customs/vies/services/checkVatService?wsdl');
?>
```

gives the following error:

```
Fatal error: Uncaught SoapFault exception: [WSDL] SOAP_ERROR: Parsing WSDL: Couldn't load from 'http://ec.europa.eu/taxation_customs/vies/services/checkVatService?wsdl'
```

curl shows the server is throwing out a 302 redirect:

```
curl -I http://ec.europa.eu/taxation_customs/vies/services/checkVatService?wsdl
HTTP/1.1 302 Moved Temporarily
Date: Fri, 25 Apr 2014 15:49:00 GMT
Transfer-Encoding: chunked
Server: Europa
Location: http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
```

Changing to the new location works, but it is theoretically only a temporary move.

**Comment by rbrown** [comment]
OK, I don't have a machine to rebuild HHVM on at the moment, but according to https://github.com/php/php-src/blob/PHP-5.4.28/ext/standard/http_fopen_wrapper.c#L76 the standard wrapper that is used by SoapClient should follow 20 redirects before giving up.

https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/ext_soap.cpp#L2350 is forcing it to 0 for HHVMs HttpClient.

**Comment by danslo** [comment]
Have you been able to test this? I mean, I can whip up a PR but you won't get the credit :-)

**Comment by rbrown** [comment]
I haven't, sorry. If you can test that it works please do, and take all the credit you can :)

**Comment by danslo** [comment]
Created a PR. Let's keep track of this upstream from now. 
https://github.com/facebook/hhvm/pull/2620

Thanks for the report.
