### ISSUE TITLE
preg_replace limited support

### ISSUE THREAD

**Issue by MattDunbar** [danslo/hhvm#4]
HipHop Fatal error: preg_replace is not going to be supported: Modifier /e must be used with the form f("<replacement string>") or f("<replacement string>"); in /Users/mattdunbar/Development/empty-mage/app/code/core/Mage/Core/Helper/Abstract.php on line 238

This occurs when adding a new storeview.

**Comment by danslo** [comment]
I'm trying to avoid Magento core hacks, but this can be temporarily solved using:

``` diff
diff --git app/code/core/Mage/Core/Helper/Abstract.php app/code/core/Mage/Core/Helper/Abstract.php
index 2897e56..326ce5a 100755
--- app/code/core/Mage/Core/Helper/Abstract.php
+++ app/code/core/Mage/Core/Helper/Abstract.php
@@ -235,8 +235,14 @@ abstract class Mage_Core_Helper_Abstract
      */
     public function removeTags($html)
     {
-        $html = preg_replace("# <(?![/a-z]) | (?<=\s)>(?![a-z]) #exi", "htmlentities('$0')", $html);
-        $html =  strip_tags($html);
+        $html = preg_replace_callback(
+            "# <(?![/a-z]) | (?<=\s)>(?![a-z]) #xi", 
+            function($m) {
+                return htmlentities($m[0]);
+            },
+            $html
+        );
+        $html = strip_tags($html);
         return htmlspecialchars_decode($html);
     }
```

Not saying this is optimal.

**Comment by MattDunbar** [comment]
Not sure if I'd quite consider this a hack since the eval modifier is discontinued and magento needs to update this in future versions if they want to support future PHP releases.

**Comment by speedupmate** [comment]
@MattDunbar future versions with Magento will become more and more delayed as company looses interest in providing open-source services while it's building it's enterprise line until then you are stuck with 100k and more installations of older releases , so counting on change is not an option with Magento

to avoid those core hacks and handle them properly maybe we should maintain a extension for hhvm_magento that arranges all core changes to one extension where the overwrites can be discarded as hhvm evolves and also reported to magento core team so they could take notes on those changes?

**Comment by danslo** [comment]
Thanks for your input... In this case it would mean patching the preg extension and maintaining it until the end of time. Facebook will not accept a pull request for it, I can guarantee that.

I am neither willing to continuously maintain a hhvm fork (everything will eventually be merged) nor a magento fork.

For now people will have to do with lesser functionality until Magento gets it's shit together.

**Comment by danslo** [comment]
Anyone that wants to make a Mage to extension to work around these things... Be my guest :-) I'm already occupied with stuff on HHVM side.

**Comment by speedupmate** [comment]
Sure you are and I understand that you don't wan't to maintain forks , nobody does :)

We could maintain magento extension for stuff that facebook will never accept and should be changed in magento in future releases but still allow us to on/off those changes as magento extension and would allow others to start easily with hhvm experimenting and this would also document the places that are conflicting . I'll do this if i have more time to play with hhvm besides my daily tasks 

but as for workflow i don't know how to decide if it can be fixed in hhvm or not so maybe it would be still useful if those issues were reported here and if you decide that this is absurd to put in to hhvm then it can find it's way to the extension until the time it get's changed in core

**Comment by danslo** [comment]
Yes, definitely report all errors. I'll let you know if it can be reasonably fixed or not.

**Comment by MattDunbar** [comment]
@speedupmate - I wasn't suggesting that magento will change it, just suggesting that I don't know if 'hack' is the correct way to put it.  I would more so refer to it as a fix for magento, something that magento should (but probably won't any time soon) fix.

Anyways, I'll take a look into possibly rolling this into a magento extension tomorrow, although, I don't know how realistic that'll be or if a .patch file would be a better solution.  I wouldn't want to get into using controller rewrites / extending models since it could break other extensions.

**Comment by speedupmate** [comment]
.patch would be same as editing the core so a big nono in Magentoland so don't be afraid to extend cause if you do it properly then conflicts are easy to detect and solve or at least to reverse engineer  while core rewrites are only possible to detect by diffing against clean source tree

**Comment by MattDunbar** [comment]
I'm aware of the implications of editing the core, but given that we wouldn't actually be changing functionality and only editing how an action is performed (and it will succeed with the same input/output), I'm not quite as opposed to it.  Extending will make conflicts easy to detect, patching (in this case) will never have conflicts, and will never cause any issues.

**Comment by speedupmate** [comment]
Don't get me wrong I don't imply that you don't know all that already.

but just for discussion then I think that your patch should detect then if the spoken change is not extended or overwritten in app/code/local or in app/code/community . Finding those conflicts in this case where the same functionality is already extended or rewritten is more harder in my opinion. 

my point being if we do all this as extension then it can be turned off , conflicts can be detected more easily (even by static analysis)  and isolated form other code. 

Either way patch or extension should become with warnings and tips how to detect issues

**Comment by danslo** [comment]
The first problem arrives because this is an abstract class ;) That means we need to use `app/code/local/Mage`, no ordinary rewrite possible. And this is pretty disgusting, especially in regard to upgrades. 

A core patch might even be a better solution here. Anyway I don't really care how this is done, I'll focus on HHVM and let other people worry about the rest.

**Comment by MattDunbar** [comment]
@danslo - We can extend everything that relies on this functionality from the abstract, but that could be a lot.

@speedupmate - Offering both might be a good idea.  I'd probably choose patches myself on existing builds, and the extension on new ones.

For now, I will be releasing an extension to fix this and future issues that can't be dealt with in HHVM.  I'll try to get this fix implemented in the afternoon tomorrow but can't guarantee I'll be able to get to it until EOD Thursday.

https://github.com/BuildRX/mage-hhvm-compatibility

I should be able to keep on top of maintaining the extension through updates.  Feel free to open issues there (or tag me here) if theres anything other than this you need implemented on the PHP end.

**Comment by speedupmate** [comment]
both is always the option :+1:

**Comment by MattDunbar** [comment]
I'll try to keep track of what 'core hacks' would need to be applied, no promises I'll create or maintain patch files though.

**Comment by MattDunbar** [comment]
This can be closed here if you consider relying on my extension or your core change a solution.

**Comment by danslo** [comment]
Sure :)
