### ISSUE TITLE
Unable to login to admin

### ISSUE THREAD

**Issue by cscd98** [danslo/hhvm#40]
Magento EE 1.14 with HipHop VM compiled from master today. No message gets displayed about incorrect password.

The HHVM error log is empty, the magento error log is empty, the nginx error log is empty!

**Comment by danslo** [comment]
I tracked this down, you should pass `-vServer.AllowDuplicateCookies=0` to your HHVM process.

Let me know if that solves your issue :) Please also let me know if `hhvm.server.allow_duplicate_cookies = 0` works, I currently don't have a handy ini setup ready.

edit: The ini setting works too.

**Comment by cscd98** [comment]
Are we talking about hhvm.ini or php.ini - it's recently gotten a little bit confusing! Does it get loaded by default?

I've tried either files in /etc/hhvm/ and neither setting worked, I will try -v option

Does hhvm.ini need specifying on the command line when running the vm? Also the -v option didn't work for me :(

**Comment by danslo** [comment]
I used `--config` to specify my ini file.

**Comment by cscd98** [comment]
I've added a php.ini to /etc/hhvm and specified it's use using -c and it's now working. Thanks again

**Comment by danslo** [comment]
No, thank you :+1:

**Comment by cscd98** [comment]
For some reason, this fix does not work on OS X? Unless something else is stopping me logging in, but I do not get any errors. I have the same option in my server.ini:

```
hhvm.server.allow_duplicate_cookies = 0
```

It doesn't make any difference if I use -vServer.AllowDuplicateCookies=0

**Comment by cscd98** [comment]
Going to close, it might have been something else but it's working again
