### ISSUE TITLE
Magento Third Party Module compatibility

### ISSUE THREAD

**Issue by cscd98** [danslo/hhvm#42]
Hi,

I have two third party modules that I am using with Magento - one is Nexcessnet Turpentine and the other CM Redis Cache.

The issue with Hiphop VM is that the silenced operator @ (at sign) does not suppress errors like in PHP. This means that the error logs get filled up with the silenced errors and this is generally bad.

I've created an issue upstream but nobody has had a chance to really fix the issue (it's a PHP compatibility thing). Any chance you could look?

http://www.php.net/manual/en/language.operators.errorcontrol.php

https://github.com/facebook/hhvm/issues/1710

The other issue is that the Redis code in HipHop VM does not support redis named persistent connections, which the CM Redis Cache module can use.

https://github.com/facebook/hhvm/issues/2517

**Comment by danslo** [comment]
First issue seems to be fixed. Let's track the other one (feature request, non-essential) upstream.
