### ISSUE TITLE
compiles too slow

### ISSUE THREAD

**Issue by MattDunbar** [danslo/hhvm#6]
The compiler takes too long to run.

**Comment by BuildRX** [comment]
Confirmed, I can replicate this bug.  In some cases it takes more than 30 minutes.

**Comment by MattDunbar** [comment]
Suggested fix: Use HHVM to compile the compiler for HHVM, it would be so much faster! (suggested by @ryan-inverseparadox in #magento-reddit)

**Comment by ryaan-anthony** [comment]
Confirmed, i did suggest that.

**Comment by danslo** [comment]
It's not a bug, it's a feature.

<img src="http://imgs.xkcd.com/comics/compiling.png" />
