### ISSUE TITLE
CE SOLR issue Apache_Solr_HttpTransport_FileGetContents.php

### ISSUE THREAD

**Issue by rootindex** [danslo/hhvm#7]
HipHop Fatal error: f_stream_context_set_option is not implemented yet. in /var/www/magento/includes/src/Apache_Solr_HttpTransport_FileGetContents.php on line 146

More detail on SOLR on CE:

http://ctdev.co.za/magento-solr-search-setup-for-community-edition-solr-ce/

**Comment by danslo** [comment]
Thanks for reporting this. I'll ask FB people about stream_context_set_option.

**Comment by danslo** [comment]
I will be closing this for now, as it doesn't seem to be part of standard Magento. And for the sake of my sanity, I will only be investigating issues that can be reproduced in standard installs.

This is still a bug in HHVM, so you could try to file an issue on the official repository.
